apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "easytravel"
spec:
  stages:
    - name: "dev"
      sequences:
       - name: "evaluation"
         tasks:
         - name: "evaluation"
    - name: "production"
      sequences:
       - name: "evaluation"
         tasks:
         - name: "evaluation"